library(tidyverse)
library(broom)

# Spurious Correlations are one example of how we can misinterperet associations

# Example: There is a very strong correl. b/w divorce rates and margarine consumption.
# cor = 0.93

# Misinterpreting these correl. is known as Data Dredging AKA Cherry picking

# Using monte carlo sims we can show how data dredging can give us correl. b/w
# vars that are theoretically uncorrelated
N = 25
G = 1000000
sim_data = tibble(group = rep(1:G, each = N), X = rnorm(N * G), Y = rnorm(N * G))
# The above sim simulates 1 million groups (G) of 25 (N),
# the data is random independent and normally distributed

# We know that X and Y are not correlated b/c we constructed a totally random data set
res = sim_data %>% 
  group_by(group) %>% 
  summarize(r = cor(X, Y)) %>% 
  arrange(desc(r))
res

# If we plot the data from the top correlated group, as seen in res,
# we can make a convincing plot showing that X & Y are correl.
sim_data %>% filter(group == res$group[which.max(res$r)]) %>% 
  ggplot(aes(X, Y)) +
  geom_point() +
  geom_smooth(method = "lm")

# Here is the dist. of the data generated by our sim
res %>% ggplot(aes(x = r)) + geom_histogram(binwidth = 0.1, color = "black")
# As we can see from the plot above, most correl. vals. are centered around 0,
# but our prev example picked a group in the top percentile, which is not indicative of the overall relationship (that relationship being "none")

# Our spurious data is also deceptive b/c it produces a p-val that indicates it is statistically significant.
sim_data %>% 
  filter(group == res$group[which.max(res$r)]) %>% 
  do(tidy(lm(Y ~ X, data = .)))
# p-val is waaaaaay below 0.05, indicating it is statistically significant (it isn't...)
# The above form of data dredging is known as "p-hacking"


